# Docker image: mlc-ai/package-rocm

FROM quay.io/pypa/manylinux_2_28_x86_64

# install core
COPY install/almalinux_install_core.sh /install/almalinux_install_core.sh
RUN bash /install/almalinux_install_core.sh

# install cmake
COPY install/almalinux_install_cmake.sh /install/almalinux_install_cmake.sh
RUN bash /install/almalinux_install_cmake.sh

# install llvm
COPY install/almalinux_install_llvm.sh /install/almalinux_install_llvm.sh
RUN bash /install/almalinux_install_llvm.sh

# install rocm
COPY install/almalinux_install_rocm_56.sh /install/almalinux_install_rocm.sh
RUN bash /install/almalinux_install_rocm.sh

# install vulkan sdk
COPY install/almalinux_install_vulkan_sdk.sh /install/almalinux_install_vulkan_sdk.sh
RUN bash /install/almalinux_install_vulkan_sdk.sh

# upgrade patchelf due to the bug in patchelf 0.10
# see details at https://stackoverflow.com/questions/61007071/auditwheel-repair-not-working-as-expected
COPY install/almalinux_install_patchelf.sh /install/almalinux_install_patchelf.sh
RUN bash /install/almalinux_install_patchelf.sh

# Install Conda
COPY install/almalinux_install_conda.sh /install/almalinux_install_conda.sh
RUN bash /install/almalinux_install_conda.sh
ENV PATH=/opt/conda/bin:${PATH}

# Install Python
RUN conda create -n py313 python=3.13 -y
COPY install/almalinux_install_python_package.sh /install/almalinux_install_python_package.sh
RUN bash /install/almalinux_install_python_package.sh

# Install auditwheel
COPY install/almalinux_install_auditwheel.sh /install/almalinux_install_auditwheel.sh
RUN bash /install/almalinux_install_auditwheel.sh
ENV AUDITWHEEL_PLAT=manylinux_2_28_x86_64

# Install Rust
COPY install/almalinux_install_rust.sh /install/almalinux_install_rust.sh
RUN bash /install/almalinux_install_rust.sh
