# GH actions.
name: MLC-Chat-CLI-Conda-Nightly-Apple-Silicon-Mac

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *' # 8 AM UTC -> 4 AM EDT


jobs:
  Build:
    strategy:
      matrix:
        pkg: ['mlc-chat-cli-nightly']
        sys:
          - conda_pkg_path: osx-arm64
            shell: 'bash -l {0}'

    runs-on: [self-hosted, macOS, ARM64]
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Build Conda
      env:
        CONDA_HOME: ${{ secrets.M1_MAC_CONDA_HOME }}
      run: |
        scripts/build_mlc_chat_cli_conda_apple_silicon.sh
    - name: Conda-Deploy
      if: github.ref == 'refs/heads/main'
      env:
        ANACONDA_API_TOKEN: ${{ secrets.MLC_ANACONDA_TOKEN }}
      run: >-
        anaconda upload --force --label main conda/pkg/${{ matrix.sys.conda_pkg_path }}/*.tar.bz2
